#!/usr/bin/env python3
"""Field-native prospective residual probe.

No plasticity rule is installed.

At the end of interval k, an established perspective path can already be sending signed conductive
current toward a Nethra.  This probe treats that signed current as the field's prospective current
for the next interval and compares it with the externally supplied source current that actually
arrives at k+1:

    epsilon_j(k+1) = J_j(k+1) - P_j(k)

where P_j(k) is the sum of signed incoming currents from the tested perspective branches.

This is deliberately narrower than a learning rule.  It asks only whether an existing Nethra field
can physically carry a residual that:
- shrinks for a correctly anticipated source;
- grows/sign-flips when the field overpredicts;
- remains large for an unanticipated source;
- can be reduced by multiple ordinary perspective Nethra;
- behaves symmetrically for positive and negative source current.
"""

from nethra import NethraField


def rk4(field, currents, steps=30, dt=0.03):
    for n in field.nethra:
        n.external=0.0
    for n,j in currents.items():
        n.external=float(j)
    for _ in range(steps):
        a0={n:n.activation for n in field.nethra}
        k1=field._derivative_at(a0)
        a1={n:a0[n]+0.5*dt*k1[n] for n in field.nethra}
        k2=field._derivative_at(a1)
        a2={n:a0[n]+0.5*dt*k2[n] for n in field.nethra}
        k3=field._derivative_at(a2)
        a3={n:a0[n]+dt*k3[n] for n in field.nethra}
        k4=field._derivative_at(a3)
        for n in field.nethra:
            n.activation=a0[n]+dt*(k1[n]+2*k2[n]+2*k3[n]+k4[n])/6.0
    for n in field.nethra:
        n.external=0.0


def set_strength(relation, strength):
    for conditions in relation.routes.values():
        conditions.clear()
        conditions[frozenset()]=float(strength)


def edge_g(field,a,b):
    key=frozenset((a,b))
    for x,y,g in field._edges():
        if frozenset((x,y))==key:
            return g
    raise AssertionError("edge missing")


def signed_current_into(field, receiver, supplier):
    return edge_g(field,receiver,supplier)*(supplier.activation-receiver.activation)


def make_predictors(count=1, evidence=1.0, leakage=.6, convergence_gain=0.0):
    f=NethraField(leakage=leakage, convergence_gain=convergence_gain)
    y=f.new()
    z=f.new()
    contexts=[]
    relations=[]
    for _ in range(count):
        c=f.new()
        r=f.new()
        f._route(r,(c,y),frozenset(),1)
        set_strength(r,evidence)
        contexts.append(c)
        relations.append(r)
    return f,y,z,contexts,relations


def prospective_current(field,y,relations):
    return sum(signed_current_into(field,y,r) for r in relations)


def run_prediction(count, context_current, evidence=1.0, steps=30):
    f,y,z,contexts,relations=make_predictors(count=count,evidence=evidence)
    rk4(f,{c:context_current for c in contexts},steps=steps)
    per=[signed_current_into(f,y,r) for r in relations]
    return f,y,z,contexts,relations,sum(per),per,y.activation


def test_residual_collapses_with_more_predictors():
    # Select a source magnitude in the range actually generated by two weak perspective paths.
    J=.018
    rows=[]
    for count in (0,1,2):
        if count==0:
            pred=0.0
            per=[]
            yact=0.0
        else:
            _f,_y,_z,_c,_r,pred,per,yact=run_prediction(count,1.0)
        eps=J-pred
        rows.append((count,pred,eps,abs(eps),yact,per))
    assert rows[1][3] < rows[0][3]
    assert rows[2][3] < rows[1][3]
    return rows


def test_overprediction_changes_residual_sign():
    J=.01
    rows=[]
    for context_current in (.1,.25,.5,1.0,2.0):
        _f,_y,_z,_c,_r,pred,per,yact=run_prediction(1,context_current)
        rows.append((context_current,pred,J-pred))
    assert rows[0][2] > 0.0
    assert rows[-1][2] < 0.0
    return rows


def test_wrong_target_remains_unpredicted():
    f,y,z,contexts,relations,pred,per,yact=run_prediction(1,1.0)
    J=.01
    eps_correct=J-pred
    eps_wrong_y=0.0-pred
    eps_wrong_z=J-0.0
    l1_correct=abs(eps_correct)
    l1_wrong=abs(eps_wrong_y)+abs(eps_wrong_z)
    assert l1_wrong > l1_correct
    return pred,eps_correct,eps_wrong_y,eps_wrong_z,l1_correct,l1_wrong


def test_signed_negative_prediction_is_symmetric():
    J=-.01
    _f,_y,_z,_c,_r,pred,per,yact=run_prediction(1,-1.0)
    assert pred < 0.0
    eps=J-pred

    _f2,_y2,_z2,_c2,_r2,pred_pos,per2,yact2=run_prediction(1,1.0)
    eps_pos=.01-pred_pos

    assert abs(pred + pred_pos) < 1e-12
    assert abs(eps + eps_pos) < 1e-12
    return pred,eps,pred_pos,eps_pos


def test_existing_strong_predictor_reduces_candidate_share_of_residual():
    # Two ordinary perspective relations share Y.  One is progressively strengthened.
    rows=[]
    for strong in (1.0,5.0,20.0,100.0,1000.0):
        f=NethraField(leakage=.6,convergence_gain=0.0)
        y=f.new()
        a=f.new(); c=f.new()
        cand=f.new(); base=f.new()
        f._route(cand,(a,y),frozenset(),1)
        f._route(base,(c,y),frozenset(),1)
        set_strength(cand,1.0)
        set_strength(base,strong)
        rk4(f,{a:1.0,c:1.0})
        pc=signed_current_into(f,y,cand)
        pb=signed_current_into(f,y,base)
        total=pc+pb
        share=0.0 if total==0 else pc/total
        rows.append((strong,pc,pb,total,share))
    assert all(rows[i][1] >= rows[i+1][1]-1e-12 for i in range(len(rows)-1))
    assert rows[-1][4] < rows[0][4]
    return rows


def main():
    print("residual_by_predictor_count",test_residual_collapses_with_more_predictors())
    print("overprediction_sign",test_overprediction_changes_residual_sign())
    print("wrong_target",test_wrong_target_remains_unpredicted())
    print("signed_symmetry",test_signed_negative_prediction_is_symmetric())
    print("candidate_share_under_existing_prediction",test_existing_strong_predictor_reduces_candidate_share_of_residual())
    print("all_assertions_passed")


if __name__=="__main__":
    main()
